// Centralized API path constants
// Generated by collecting all fetch('/api/...') occurrences across the codebase.

export const API = {
  // ETA
  ETA_MENU: '/api/eta/menu',
  ETA_READ: '/api/eta/read',
  ETA_UPDATE: '/api/eta/update',
  ETA_HEATING_MODE: '/api/eta/heating-mode',
  ETA_READ_BATCH_MENU_DATA: '/api/eta/readBatchMenuData',
  ETA_RAW: '/api/eta/raw',

  // Config
  CONFIG: '/api/config',

  // Misc
  LOGS: '/api/logs',
  BACKGROUND_STATUS: '/api/background/status',
  CHANNEL_NAMES: '/api/channelnames',
  WEATHER: '/api/weather',
} as const;
